### ISSUE TITLE
Open Questions ?

### ISSUE THREAD

**Issue by ABresting** [ABresting/HPX-stack-overflow#1]
[Link](https://www.dropbox.com/s/kmme08s7z2ib2j0/threading_paper_preprint.pdf?dl=0) Questions have arisen from this question paper.

**In** the research paper, What are the components of the HPX thread's context, are they machine/OS specific and are they portable? 

_"While execution of an HPX-thread may_
_never be resumed, a terminated HPX-thread still has a global_
_name and therefore is still a first class object."_

**How** does this happen and why even after permanent suspension, or is there a catch when you say "may never be resumed"? How you distinguish between permanent and temporary suspension? Also, if there is any garbage collector for GID/ global name involved?

**I assume** a thread can resume its execution, so underneath some interrupt occurs and generates a signal and triggers/event some waking up feature, right?

**Comment by brycelelbach** [comment]
> Components of an HPX thread context

The components of an HPX thread's context are:

* Thread local storage.
* Thread stack.

An HPX-thread is more than that, though: it consists of:

* A function to execute.
* A status.
* A context.
* Thread meta data.

> Is the thread context portable?

The thread context is architecture/OS specific. A "task description" (e.g. a thread that has not yet been given a context) is not quite so architecture/OS specific.

> "While execution of an HPX-thread may never be resumed, a terminated HPX-thread still has a global name and therefore is still a first class object."

Hrm. Not sure why I felt that sentence needed to be added there.. I also suspect it is not true today that HPX threads have GIDs (hpx::thread might?).

To a degree, this is more a matter of concept/theory:

* For something to be a first-class entity in HPX, does it have to have a GID?
* Are HPX-threads first-class entities in HPX?

I lean towards "no" for #1 and "yes" for #2. Constructs like threads and local futures are fundamental primitives in HPX, even without a global name.

I wouldn't worry about this, though; it shouldn't affect the scope of this project.

> How does this happen and why even after permanent suspension, or is there a catch when you say "may never be resumed"? 

I'm pretty sure the significance was only conceptual; I was differentiating when a work item is encapsulated in a thread (e.g. difference between thread description and thread). An HPX-thread will never be resumed after it is terminated - there's no catch.

> How you distinguish between permanent and temporary suspension? 

I'm not sure what the distinction would be - do you mean "between thread termination and temporary suspension?". "terminated" is one distinct thread state, and a thread never returns from that state to "active". "suspended" is a temporary state; eventually the thread will be "active" again, and eventually will reach a "terminated" state (otherwise you have a deadlock).
